# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0003_auto_20171108_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('H', 'History'), ('C', 'Classic'), ('F', 'Fiction'), ('NF', 'Non-fiction'), ('M', 'Mystery'), ('B', 'Biography'), ('BS', 'Best seller')], max_length=200),
        ),
    ]
