# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0004_auto_20171121_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='my_bookstore.Author'),
            preserve_default=False,
        ),
    ]
