# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
