# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0008_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_bookstore.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_bookstore.Book'),
        ),
    ]
